DES_Empleados/Models/ProjectAssignment.cs
using System.ComponentModel.DataAnnotations;

namespace DES_Empleados.Models
{
    public class ProjectAssignment
    {
        // asignación de empleados a proyectos, especificando la fecha de asignación y un rol específico que desempeña el empleado en el proyecto.
        
        [Required]
        public int Id { get; set; }

        [Required]
        public int? EmployeeId { get; set; }

        public Employee? Employee { get; set; }

        [Required]
        public int? ProjectId { get; set; }

        public Project? Project { get; set; }

        [Required]
        [Display(Name = "Assignment date")]
        [DataType(DataType.Date)]
        public DateTime AssignmentDate { get; set; }

        [Required]
        [StringLength(50)]
        public string Rol { get; set; }
    }
}

DES_Empleados/Controllers/ProjectAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DES_Empleados.Models;

namespace DES_Empleados.Controllers
{
    public class ProjectAssignmentsController : Controller
    {
        private readonly EmployeesDBContext _context;

        public ProjectAssignmentsController(EmployeesDBContext context)
        {
            _context = context;
        }

        // GET: ProjectAssignments
        public async Task<IActionResult> Index(string searchString)
        {
            if(_context.ProjectAssignments == null)
            {
                return Problem("El contexto es nulo.");
            }

            
                var projectAssignment = _context.ProjectAssignments.Include(p => p.Employee).Include(p => p.Project).Where(s => string.IsNullOrEmpty(searchString) || s.Project.Name!.Contains(searchString));
            //var employeesDBContext = _context.ProjectAssignments.Include(p => p.Employee).Include(p => p.Project);
            return View(await projectAssignment.ToListAsync());
        }

        // GET: ProjectAssignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectAssignment = await _context.ProjectAssignments
                .Include(p => p.Employee)
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectAssignment == null)
            {
                return NotFound();
            }

            return View(projectAssignment);
        }

        // GET: ProjectAssignments/Create
        public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Lastname");
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description");
            return View();
        }

        // POST: ProjectAssignments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EmployeeId,ProjectId,AssignmentDate,Rol")] ProjectAssignment projectAssignment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectAssignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Lastname", projectAssignment.EmployeeId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description", projectAssignment.ProjectId);
            return View(projectAssignment);
        }

        // GET: ProjectAssignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectAssignment = await _context.ProjectAssignments.FindAsync(id);
            if (projectAssignment == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Lastname", projectAssignment.EmployeeId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description", projectAssignment.ProjectId);
            return View(projectAssignment);
        }

        // POST: ProjectAssignments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EmployeeId,ProjectId,AssignmentDate,Rol")] ProjectAssignment projectAssignment)
        {
            if (id != projectAssignment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectAssignment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectAssignmentExists(projectAssignment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Lastname", projectAssignment.EmployeeId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description", projectAssignment.ProjectId);
            return View(projectAssignment);
        }

        // GET: ProjectAssignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectAssignment = await _context.ProjectAssignments
                .Include(p => p.Employee)
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectAssignment == null)
            {
                return NotFound();
            }

            return View(projectAssignment);
        }

        // POST: ProjectAssignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectAssignment = await _context.ProjectAssignments.FindAsync(id);
            if (projectAssignment != null)
            {
                _context.ProjectAssignments.Remove(projectAssignment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectAssignmentExists(int id)
        {
            return _context.ProjectAssignments.Any(e => e.Id == id);
        }
    }
}

DES_Empleados/Views/ProjectAssignments/Create.cshtml
@model DES_Empleados.Models.ProjectAssignment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProjectAssignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class ="form-control" asp-items="ViewBag.EmployeeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class ="form-control" asp-items="ViewBag.ProjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AssignmentDate" class="control-label"></label>
                <input asp-for="AssignmentDate" class="form-control" />
                <span asp-validation-for="AssignmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rol" class="control-label"></label>
                <input asp-for="Rol" class="form-control" />
                <span asp-validation-for="Rol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DES_Empleados/Views/ProjectAssignments/Delete.cshtml
@model DES_Empleados.Models.ProjectAssignment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectAssignment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignmentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rol)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DES_Empleados/Views/ProjectAssignments/Details.cshtml
@model DES_Empleados.Models.ProjectAssignment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProjectAssignment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignmentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rol)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DES_Empleados/Views/ProjectAssignments/Edit.cshtml
@model DES_Empleados.Models.ProjectAssignment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProjectAssignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignmentDate" class="control-label"></label>
                <input asp-for="AssignmentDate" class="form-control" />
                <span asp-validation-for="AssignmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rol" class="control-label"></label>
                <input asp-for="Rol" class="form-control" />
                <span asp-validation-for="Rol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DES_Empleados/Views/ProjectAssignments/Index.cshtml
@model IEnumerable<DES_Empleados.Models.ProjectAssignment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="ProjectAssignments" asp-action="Index" method="GET">
    <p>
        Título: <input type="text" name="SearchString" />
        <input type="submit" value="Filtrar"/>
    </p>
    </form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssignmentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rol)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignmentDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rol)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>